version: '2.2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: sharepointoscar/cars-api:v4
    ports:
      - '1337:1337'
    environment:
      - NODE_ENV=development
      - PORT=1337
      - MONGODB_HOST=localhost
      - MONGODB_PORT=27017
      - MONGODB_URI=mongodb://mongoadmin:password01@database:27017/cars_api?authSource=admin
      - MONGODB_USERNAME=mongoadmin
      - MONGODB_PASSWORD=password01
      - ENABLE_ELASTICSEARCH=true
      - ELASTICSEARCH_URL=http://localhost:9200
      - DISABLE_SAILS_SEED=false
      - DISABLE_GRAPHQL=true
    depends_on: 
      - database
  database:
    image: mongo:4.0
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password01
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /Users/omedina/Documents:/var/lib/mongodb

  elasticsearch:
    image: elasticsearch:7.5.0
    environment:
      - cluster.name=oscar-search
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - transport.host=127.0.0.1
      #- transport.tcp.port=9300
      #- http.port=9200
      - http.host=127.0.0.1
      - network.host=127.0.0.1
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.routing.allocation.disk.watermark.low=2gb
      - cluster.routing.allocation.disk.watermark.high=1gb
      - cluster.routing.allocation.disk.watermark.flood_stage=512mb
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
  
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  kibana:
    image: kibana:7.5.0
    environment: 
      - opendistro_security.multitenancy.enabled=false
    ports:
      - "5601:5601"