dependencies:
- name: mongodb
  alias: cars-rest-api-db
  version: 7.6.5
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: cars-rest-api-db.enabled

- name: elastic-stack
  alias: elk
  version: 1.8.0
  repository: https://kubernetes-charts.storage.googleapis.com
  condition. elk.enabled