{{- if .Values.knativeDeploy }}
{{- else }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      rollme: {{ randAlphaNum 5 | quote }} 
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
            - name: MONGODB_URI
              value: "mongodb://{{.Values.env.MONGODB_USERNAME}}:{{.Values.env.MONGODB_PASSWORD}}@{{ template "mongodb.fullname" . }}-db:27017/cars_rest_api"
            - name: MONGODB_HOST
              value: "{{ template "mongodb.fullname" . }}-db"  
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USERNAME
              value: {{.Values.env.MONGODB_USERNAME}}
            - name: MONGODB_PASSWORD
              value: {{.Values.env.MONGODB_PASSWORD}}
            - name: MONGODB_ROOT_PASSWORD
              value: {{.Values.env.MONGODB_ROOT_PASSWORD}} 
            - name: MONGODB_DATABASE
              value: {{.Values.env.MONGODB_DATABASE}} 
            - name: ELASTICSEARCH_URL
              value: {{ .Release.Name }}-elasticsearch-client:9200
            - name: ENABLE_ELASTICSEARCH
              value: "true"
            - name: DISABLE_SAILS_SEED
              value: "false"

        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probePath }}
            port: {{ .Values.service.internalPort }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
{{- end }}