apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  mongodb-username: YWRtaW4=
  mongodb-password: UGFzc3dvcmQx
  rootpassword: UGFzc3dvcmQx
  mongodb-root-password: UGFzc3dvcmQx