apiVersion: v1
kind: Secret
metadata:
  name: mongodb-auth
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  username: {{ .Values.mongodbUsername }}
  password: {{ .Values.mongodbPassword }}
  rootpassword: {{.Values.mongodbPassword}}